language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
  - make dep
install:
  - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; else make build; fi
  - make build 
script:
  # - make lint
  - make fmt-check
  - make test
 after_success:
   - bash <(curl -s https://codecov.io/bash)
  
